export const mockData = {
  admin: {
    stats: [
      {
        label: "Total Users",
        value: "12,450",
        delta: "",
        tone: "cool",
        icon: "users",
        points:
          "0,18 9,15 18,17 27,13 36,10 45,11 54,8 64,9 74,7 84,6 94,8 100,7",
      },
      {
        label: "Active Users",
        value: "3,220",
        delta: "+ 5.4%",
        tone: "cool",
        icon: "activity",
        points:
          "0,19 9,16 18,17 27,14 36,12 45,13 54,10 64,8 74,9 84,7 94,8 100,6",
      },
      {
        label: "Total Apps",
        value: "150",
        delta: "",
        tone: "cool",
        icon: "apps",
        points:
          "0,16 9,14 18,15 27,12 36,9 45,10 54,8 64,6 74,7 84,8 94,9 100,8",
      },
      {
        label: "Revenue",
        value: "$18,750",
        delta: "",
        tone: "mint",
        icon: "billing",
        points:
          "0,20 9,17 18,15 27,13 36,12 45,10 54,8 64,9 74,7 84,6 94,4 100,3",
      },
      {
        label: "Open Tickets",
        value: "34",
        delta: "",
        tone: "cool",
        icon: "tickets",
        points:
          "0,18 9,16 18,14 27,12 36,11 45,12 54,13 64,14 74,13 84,12 94,11 100,10",
      },
    ],
    users: [
      {
        id: "001",
        name: "John Doe",
        email: "john.doe@example.com",
        role: "Admin",
        joinedOn: "Today",
        status: "Active",
        isActive: true,
      },
      {
        id: "002",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        role: "Editor",
        joinedOn: "23 Aug 2025",
        status: "Active",
        isActive: true,
      },
      {
        id: "003",
        name: "Michael Brown",
        email: "michael.brown@example.com",
        role: "User",
        joinedOn: "22 Aug 2025",
        status: "Inactive",
        isActive: false,
      },
      {
        id: "004",
        name: "Emily Clark",
        email: "emily.clark@example.com",
        role: "User",
        joinedOn: "21 Aug 2025",
        status: "Active",
        isActive: true,
      },
      {
        id: "005",
        name: "David Wilson",
        email: "david.wilson@example.com",
        role: "User",
        joinedOn: "20 Aug 2025",
        status: "Pending",
        isActive: false,
      },
      {
        id: "006",
        name: "Sarah Lee",
        email: "sarah.lee@example.com",
        role: "Editor",
        joinedOn: "19 Aug 2025",
        status: "Inactive",
        isActive: false,
      },
      {
        id: "007",
        name: "Chris Johnson",
        email: "chris.johnson@example.com",
        role: "User",
        joinedOn: "18 Aug 2025",
        status: "Active",
        isActive: true,
      },
      {
        id: "008",
        name: "Lisa White",
        email: "lisa.white@example.com",
        role: "User",
        joinedOn: "17 Aug 2025",
        status: "Inactive",
        isActive: false,
      },
      {
        id: "009",
        name: "Ava Miller",
        email: "ava.miller@example.com",
        role: "Admin",
        joinedOn: "16 Aug 2025",
        status: "Active",
        isActive: true,
      },
      {
        id: "010",
        name: "Liam Davis",
        email: "liam.davis@example.com",
        role: "User",
        joinedOn: "15 Aug 2025",
        status: "Pending",
        isActive: false,
      },
      {
        id: "011",
        name: "Noah Taylor",
        email: "noah.taylor@example.com",
        role: "Editor",
        joinedOn: "14 Aug 2025",
        status: "Active",
        isActive: true,
      },
      {
        id: "012",
        name: "Mia Anderson",
        email: "mia.anderson@example.com",
        role: "User",
        joinedOn: "13 Aug 2025",
        status: "Inactive",
        isActive: false,
      },
    ],
    apps: [
      {
        name: "KYC Manager",
        category: "Compliance",
        owner: "Ops Team",
        health: "Healthy",
      },
      {
        name: "Invoice Hub",
        category: "Billing",
        owner: "Finance Team",
        health: "Warning",
      },
      {
        name: "Org Registry",
        category: "Operations",
        owner: "Admin Team",
        health: "Healthy",
      },
      {
        name: "Support Console",
        category: "Support",
        owner: "Support Team",
        health: "Healthy",
      },
    ],
    payments: [
      {
        user: "John Doe",
        initials: "JD",
        time: "10 mins ago",
        amount: "$120.00",
        status: "Paid",
      },
      {
        user: "Sarah Lee",
        initials: "SL",
        time: "1 hour ago",
        amount: "$85.00",
        status: "Paid",
      },
      {
        user: "Michael Smith",
        initials: "MS",
        time: "3 hours ago",
        amount: "$56.00",
        status: "Failed",
      },
      {
        user: "Emily Clark",
        initials: "EC",
        time: "1 day ago",
        amount: "$99.00",
        status: "Paid",
      },
    ],
    tickets: [
      {
        id: "TK-2201",
        userName: "John Doe",
        userEmail: "john.doe@example.com",
        subject: "Login issue after password reset",
        description:
          "User is unable to sign in after resetting password. The reset flow finishes successfully, but login still returns invalid credentials.",
        status: "Open",
        priority: "High",
        date: "2026-03-27",
        conversation: [
          {
            id: "m-1",
            sender: "user",
            text: "I reset my password but still cannot log in.",
            time: "09:15 AM",
          },
          {
            id: "m-2",
            sender: "admin",
            text: "Thanks for reporting. We are checking your account status now.",
            time: "09:22 AM",
          },
        ],
      },
      {
        id: "TK-2194",
        userName: "Sarah Lee",
        userEmail: "sarah.lee@example.com",
        subject: "Invoice shows duplicate charge",
        description:
          "March invoice contains a duplicate transaction entry for the same order reference.",
        status: "Pending",
        priority: "Medium",
        date: "2026-03-25",
        conversation: [
          {
            id: "m-3",
            sender: "user",
            text: "I was charged twice for one payment.",
            time: "11:08 AM",
          },
        ],
      },
      {
        id: "TK-2179",
        userName: "Emily Clark",
        userEmail: "emily.clark@example.com",
        subject: "Need CSV export in profile page",
        description:
          "Requested CSV export option for activity history inside profile section.",
        status: "Resolved",
        priority: "Low",
        date: "2026-03-22",
        conversation: [
          {
            id: "m-4",
            sender: "user",
            text: "Can we export activity history as CSV?",
            time: "03:10 PM",
          },
          {
            id: "m-5",
            sender: "admin",
            text: "Great suggestion. We have added this to roadmap.",
            time: "03:35 PM",
          },
        ],
      },
    ],
    activityFeed: [
      { time: "10 mins ago", event: "New user registered", meta: "" },
      { time: "2 hrs ago", event: 'App "Task Manager" added', meta: "" },
      { time: "4 hrs ago", event: "Payment of $56.00 failed", meta: "" },
    ],
    userGrowth: [1200, 3600, 3300, 5600, 4300, 6500, 7800, 9800],
  },
  home: {
    stats: [
      {
        title: "All Apps",
        value: "5 Apps",
        hint: "Browse your workspace",
        accent: "#2563eb",
        route: "/all-apps",
        action: "Explore apps",
      },
      {
        title: "Active Subscriptions",
        value: "3 Subscribed",
        hint: "Renewals running smoothly",
        accent: "#0f766e",
        route: "/all-apps",
        action: "Manage plans",
      },
      {
        title: "My Tickets",
        value: "8",
        hint: "2 need attention",
        accent: "#ea580c",
        route: "/activity",
        action: "View activity",
      },
    ],
    transactions: [
      {
        id: "Invoice #2099",
        time: "2 days ago",
        amount: "₹2,500",
        status: "Paid",
        color: "#2563eb",
      },
      {
        id: "Auto-Renewal",
        time: "6 days ago",
        amount: "₹2,500",
        status: "Paid",
        color: "#2563eb",
      },
      {
        id: "Invoice #2086",
        time: "9 days ago",
        amount: "₹5,000",
        status: "Failed",
        color: "#f59e0b",
      },
      {
        id: "Invoice #2079",
        time: "2 weeks ago",
        amount: "₹750",
        status: "Paid",
        color: "#2563eb",
      },
    ],
    apps: [
      {
        name: "Application Management",
        time: "2 days ago",
        color: "#38bdf8",
        description: "Manage apps, policies and deployment activity.",
        route: "/all-apps",
      },
      {
        name: "CRM System",
        time: "6 days ago",
        color: "#4f46e5",
        description: "Track customer records and sales workflows.",
        route: "/my-apps",
      },
      {
        name: "Charge Management",
        time: "10 days ago",
        color: "#f59e0b",
        description: "Monitor payments, invoices and charges.",
        route: "/all-apps",
      },
      {
        name: "Document Management",
        time: "1 week ago",
        color: "#f97316",
        description: "Review company documents and approvals.",
        route: "/my-apps",
      },
    ],
    recommendedActions: [
      {
        title: "Complete KYC verification",
        description: "Unlock the full set of apps and faster approvals.",
        action: "Go to settings",
        route: "/settings",
        color: "#2563eb",
      },
      {
        title: "Review open tickets",
        description: "Check unresolved requests and recent platform updates.",
        action: "Open activity",
        route: "/activity",
        color: "#f97316",
      },
      {
        title: "Explore more tools",
        description:
          "Discover additional apps that match your current workflow.",
        action: "See all apps",
        route: "/all-apps",
        color: "#7c3aed",
      },
    ],
    recentRight: [
      { title: "Subscription renewed", time: "2 days ago", status: "" },
      { title: "Opened CRM System", time: "6 days ago", status: "Open" },
      { title: "Invoice #2086", time: "6 days ago", status: "Failed" },
      { title: "Invoice #2079", time: "2 weeks ago", status: "Paid" },
    ],
    usageBreakdown: [
      { app: "CRM System", used: "4h 20m", percent: 82, color: "#2563eb" },
      {
        app: "Charge Management",
        used: "2h 45m",
        percent: 54,
        color: "#0ea5e9",
      },
      {
        app: "Application Management",
        used: "1h 18m",
        percent: 33,
        color: "#22c55e",
      },
    ],
  },
  appCatalog: {
    allApps: [
      {
        id: 1,
        name: "Document Management",
        description: "Manage and organize all your documents efficiently.",
        detail:
          "A full-suite document workspace with version control, comments, and workflows.",
        category: "Productivity",
        status: "active",
        subscribed: true,
        wishlisted: false,
      },
      {
        id: 2,
        name: "Application Management",
        description: "Monitor, deploy, and manage business applications.",
        detail:
          "Track app health, enforce policies, and get analytics across all environments.",
        category: "DevOps",
        status: "active",
        subscribed: true,
        wishlisted: true,
      },
      {
        id: 3,
        name: "Charge Management",
        description: "Billing and payment processing for apps and services.",
        detail:
          "Declarative invoice generation, audit logs, and smart cost predictions.",
        category: "Finance",
        status: "available",
        subscribed: false,
        wishlisted: false,
      },
      {
        id: 4,
        name: "Overview Purchasing",
        description: "Procurement dashboard for orders and approvals.",
        detail:
          "Run purchase cycles, supplier ratings, and spending limits + reports.",
        category: "Finance",
        status: "available",
        subscribed: false,
        wishlisted: true,
      },
      {
        id: 5,
        name: "Software Constraints",
        description: "Govern constraints, compliance and policy enforcement.",
        detail:
          "Set rules for permissions, license checks, and secure usage across the company.",
        category: "Security",
        status: "available",
        subscribed: false,
        wishlisted: false,
      },
      {
        id: 6,
        name: "User Analytics",
        description: "Data insights on user behavior and resource usage.",
        detail:
          "Drill into adoption metrics, funnel analytics, and health scores.",
        category: "Analytics",
        status: "beta",
        subscribed: false,
        wishlisted: false,
      },
    ],
    myApps: [
      {
        id: 1,
        name: "Document Management",
        description: "Manage and organize all your documents efficiently",
        category: "Productivity",
        lastUsed: "2 hours ago",
        usage: "85%",
      },
      {
        id: 2,
        name: "Application Management",
        description: "Monitor and control application deployments",
        category: "DevOps",
        lastUsed: "1 day ago",
        usage: "62%",
      },
      {
        id: 3,
        name: "Charge Management",
        description: "Handle billing and payment processing",
        category: "Finance",
        lastUsed: "3 days ago",
        usage: "41%",
      },
    ],
    favorites: [
      {
        id: 1,
        name: "Document Management",
        description: "Manage and organize all your documents efficiently",
        category: "Productivity",
        favoritedDate: "2024-03-20",
        rating: 5,
      },
      {
        id: 2,
        name: "User Analytics",
        description: "Analyze user behavior and engagement",
        category: "Analytics",
        favoritedDate: "2024-03-18",
        rating: 4,
      },
    ],
  },
  activity: [
    {
      id: 1,
      type: "subscription",
      title: "Subscribed to Document Management",
      description: "You successfully subscribed to Document Management app.",
      timestamp: "2026-03-26T10:30:00Z",
      status: "success",
    },
    {
      id: 2,
      type: "login",
      title: "Logged in",
      description: "Successful login from Chrome on Windows.",
      timestamp: "2026-03-26T09:15:00Z",
      status: "info",
    },
    {
      id: 3,
      type: "payment",
      title: "Payment processed",
      description: "Monthly subscription payment of $29.99 was processed.",
      timestamp: "2026-03-25T14:20:00Z",
      status: "success",
    },
    {
      id: 4,
      type: "update",
      title: "Profile updated",
      description: "Your profile information has been updated.",
      timestamp: "2026-03-25T11:45:00Z",
      status: "info",
    },
    {
      id: 5,
      type: "error",
      title: "Failed login attempt",
      description: "Unsuccessful login attempt from unknown device.",
      timestamp: "2026-03-24T16:10:00Z",
      status: "error",
    },
  ],
  profile: {
    fullName: "Rohan Kumar",
    email: "rohan@example.com",
    phone: "+91 9876543210",
    role: "User",
    photo: null,
    kycStatus: "Pending",
  },
  settings: {
    theme: "light",
    language: "en",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: false,
    twoFactor: false,
    dataSharing: true,
  },
  plans: [
    {
      id: "basic",
      name: "Basic",
      tag: "Start Here",
      tagStyle: "blue",
      priceMonthly: 499,
      priceYearly: 1499,
      icon: "person",
      features: [
        "Access to basic application",
        "Email support",
        "Up to 5 request per month",
      ],
    },
    {
      id: "standard",
      name: "Standard",
      tag: "Most Popular",
      tagStyle: "orange",
      priceMonthly: 999,
      priceYearly: 2999,
      icon: "star",
      features: [
        "Access to all application",
        "Priority email & chat support",
        "Up to 20 requests per month",
      ],
    },
    {
      id: "premium",
      name: "Premium",
      tag: "Best Value",
      tagStyle: "blue",
      priceMonthly: 1999,
      priceYearly: 3999,
      icon: "diamond",
      features: [
        "Access to all application",
        "Dedicated account manager",
        "Unlimited requests",
      ],
    },
  ],
};
